FROM python
RUN pip install flask
COPY  ./static /home/labs/static/
COPY  ./templates /home/labs/templates/
COPY  design_app.py /home/labs/
EXPOSE 5050
CMD python /home/labs/design_app.py
FROM python
RUN pip install flask
COPY  ./static /home/labs/static/
COPY  ./templates /home/labs/templates/
COPY  design_app.py /home/labs/
EXPOSE 5050
CMD python /home/labs/design_app.py
